logging:
  level:
    root: DEBUG
    org.mongodb.driver.cluster: INFO
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO

server:
  session:
    timeout: 3600 # 1 hour

spring:
  data:
    elasticsearch:
      cluster-name: jakduk-elasticsearch
      cluster-nodes: 192.168.35.137:9300,192.168.35.181:9300
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.35.74
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3

mongo:
  db:
    name: jakduk_test
  host:
    name: http://192.168.35.194:27017,http://192.168.35.138:27017

api:
  api-server-url: http://localhost:8080
  web-server-url: http://localhost:3000
  remember-me-expiration: 7200 # 2 hours
  swagger: # swagger
    protocol: http
    host: localhost:8080
  slackLog: # alert slack
    enabled: false
    level: DEBUG
    webhook: https://hooks.slack.com/services/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
    channel: #jakduk_staging_log
    username: \uC791\uB450\uD0B9 \uC2EC\uD310

core:
  elasticsearch:
    index-board: jakduk_dev_board
    index-gallery: jakduk_dev_gallery
    index-search-word: jakduk_dev_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50
  rabbitmq:
    exchange-name: jakduk-dev
    queues:
      email:
        binding-queue-name: dev.email
        binding-routing-key: dev.email.*
        enabled: true
      elasticsearch:
        binding-queue-name: dev.elasticsearch
        binding-routing-key: dev.elasticsearch.*
        enabled: true
    routing-keys:
      email-welcome: dev.email.welcome
      email-reset-password: dev.email.reset-password
      elasticsearch-index-document-board: dev.elasticsearch.index-document-board
      elasticsearch-delete-document-board: dev.elasticsearch.delete-document-board
      elasticsearch-index-document-comment: dev.elasticsearch.index-document-comment
      elasticsearch-delete-document-comment: dev.elasticsearch.delete-document-comment
      elasticsearch-index-document-gallery: dev.elasticsearch.index-document-gallery
      elasticsearch-delete-document-gallery: dev.elasticsearch.delete-document-gallery
      elasticsearch-index-document-search-word: dev.elasticsearch.index-document-search-word
  slack:
    board:
      channel: '#jakduk_board_noti'
      enabled: false
      webhook: https://hooks.slack.com/services/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
  storage:
    image:
      path: /Users/pyohwanjang/storage/image/
    thumbnail:
      path: /Users/pyohwanjang/storage/thumbnail/
    user:
      picture:
        large:
          path: /Users/pyohwanjang/storage/user/picture/large/
        small:
          path: /Users/pyohwanjang/storage/user/picture/small/