logging:
  file: /jakduk/api/logs/api.log
  level:
    root: INFO

server:
  session:
    timeout: 259200 # 3 days

spring:
  data:
    elasticsearch:
      cluster-name: jakduk-elasticsearch
      cluster-nodes: 192.168.35.137:9300,192.168.35.181:9300
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.35.74
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3

jakduk:
  api-server-url: https://api.jakduk.com
  web-server-url: https://jakduk.com
  remember-me-expiration: 2592000 # 1 month

  mongodb:
    database: jakduk_sample
    host: http://192.168.35.194:27017,http://192.168.35.138:27017
  slackLog: # alert slack
    enabled: true
    level: ERROR
    webhook: https://hooks.slack.com/services/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
    channel: #jakduk_log
    username: \uC791\uB450\uD0B9 \uC2EC\uD310
  elasticsearch:
    index-board: jakduk_prd_board
    index-gallery: jakduk_prd_gallery
    index-search-word: jakduk_prd_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50
  rabbitmq:
    exchange-name: jakduk-prd
    queues:
      email:
        binding-queue-name: prd.email
        binding-routing-key: prd.email.*
        enabled: true
      elasticsearch:
        binding-queue-name: prd.elasticsearch
        binding-routing-key: prd.elasticsearch.*
        enabled: true
    routing-keys:
      email-welcome: prd.email.welcome
      email-reset-password: prd.email.reset-password
      elasticsearch-index-document-article: prd.elasticsearch.index-document-article
      elasticsearch-delete-document-article: prd.elasticsearch.delete-document-article
      elasticsearch-index-document-article-comment: prd.elasticsearch.index-document-article-comment
      elasticsearch-delete-document-article-comment: prd.elasticsearch.delete-document-article-comment
      elasticsearch-index-document-gallery: prd.elasticsearch.index-document-gallery
      elasticsearch-delete-document-gallery: prd.elasticsearch.delete-document-gallery
      elasticsearch-index-document-search-word: prd.elasticsearch.index-document-search-word
  storage:
    image-path: /jakduk/storage/image/
    thumbnail-path: /jakduk/storage/thumbnail/
    user-picture-large-path: /jakduk/storage/user/picture/large/
    user-picture-small-path: /jakduk/storage/user/picture/small/
