logging:
  pattern:
    file: "%d{ISO8601} [%thread] [%-5level] [%logger{0}.%M:%line] - %msg%n%rEx"
  file: /jakduk/api/logs/api.log
  level:
    root: INFO

server:
  servlet:
    session:
      timeout: 1d

spring:
  data:
    elasticsearch:
      cluster-name: jakduk-elasticsearch
      cluster-nodes: 192.168.55.199:9300,192.168.55.54:9300
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.55.156
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3

jakduk:
  api-server-url: https://api.jakduk.com
  web-server-url: https://jakduk.com
  remember-me-expiration: 2592000 # 1 month

  mongodb:
    database: jakduk_sample
    host: http://192.168.55.25:27017,http://192.168.55.163:27017
  elasticsearch:
    index-board: jakduk_prd_board
    index-gallery: jakduk_prd_gallery
    index-search-word: jakduk_prd_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50
  rabbitmq:
    exchange-name: jakduk-prd
    queues:
      email:
        binding-queue-name: prd.email
        binding-routing-key: prd.email.*
        enabled: true
      elasticsearch:
        binding-queue-name: prd.elasticsearch
        binding-routing-key: prd.elasticsearch.*
        enabled: true
    routing-keys:
      email-welcome: prd.email.welcome
      email-reset-password: prd.email.reset-password
      elasticsearch-index-document-article: prd.elasticsearch.index-document-article
      elasticsearch-delete-document-article: prd.elasticsearch.delete-document-article
      elasticsearch-index-document-article-comment: prd.elasticsearch.index-document-article-comment
      elasticsearch-delete-document-article-comment: prd.elasticsearch.delete-document-article-comment
      elasticsearch-index-document-gallery: prd.elasticsearch.index-document-gallery
      elasticsearch-delete-document-gallery: prd.elasticsearch.delete-document-gallery
      elasticsearch-index-document-search-word: prd.elasticsearch.index-document-search-word
  storage:
    image-path: /jakduk/storage/image/
    thumbnail-path: /jakduk/storage/thumbnail/
    user-picture-large-path: /jakduk/storage/user/picture/large/
    user-picture-small-path: /jakduk/storage/user/picture/small/
