logging:
  file: /jakduk/api/logs/api.log
  level:
    root: INFO
    org.mongodb.driver.cluster: INFO

server:
  session:
    timeout: 7200 # 2 hours

spring:
  data:
    elasticsearch:
      cluster-name: jakduk-elasticsearch
      cluster-nodes: 192.168.35.137:9300,192.168.35.181:9300
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.35.74
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3

jakduk:
  api-server-url: https://dev-web.jakduk.com/api
  web-server-url: https://dev-web.jakduk.com
  remember-me-expiration: 14400 # 4 hours

  mongodb:
    database: jakduk_test
    host: http://192.168.35.194:27017,http://192.168.35.138:27017
  swagger: # swagger
    protocol: https
    host: dev-web.jakduk.com
  slackLog: # alert slack
    enabled: true
    level: WARN
    webhook: https://hooks.slack.com/services/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
    channel: #jakduk_staging_log
    username: \uC791\uB450\uD0B9 \uC2EC\uD310
  elasticsearch:
    index-board: jakduk_dev_board
    index-gallery: jakduk_dev_gallery
    index-search-word: jakduk_dev_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50
  rabbitmq:
    exchange-name: jakduk-dev
    queues:
      email:
        binding-queue-name: dev.email
        binding-routing-key: dev.email.*
        enabled: true
      elasticsearch:
        binding-queue-name: dev.elasticsearch
        binding-routing-key: dev.elasticsearch.*
        enabled: true
    routing-keys:
      email-welcome: dev.email.welcome
      email-reset-password: dev.email.reset-password
      elasticsearch-index-document-board: dev.elasticsearch.index-document-board
      elasticsearch-delete-document-board: dev.elasticsearch.delete-document-board
      elasticsearch-index-document-comment: dev.elasticsearch.index-document-comment
      elasticsearch-delete-document-comment: dev.elasticsearch.delete-document-comment
      elasticsearch-index-document-gallery: dev.elasticsearch.index-document-gallery
      elasticsearch-delete-document-gallery: dev.elasticsearch.delete-document-gallery
      elasticsearch-index-document-search-word: dev.elasticsearch.index-document-search-word
  storage:
    image-path: /jakduk/storage/image/
    thumbnail-path: /jakduk/storage/thumbnail/
    user-picture-large-path: /jakduk/storage/user/picture/large/
    user-picture-small-path: /jakduk/storage/user/picture/small/