spring:
  profiles:
    include: core-staging

server:
  session:
    timeout: 7200 # 2 hours

logging:
  file: /jakduk/api/logs/api.log
  level:
    root: DEBUG
    org.mongodb.driver.cluster: INFO

api:
  api-server-url: https://staging.jakduk.com:8080
  web-server-url: https://staging.jakduk.com
  remember-me-expiration: 14400 # 4 hours
  swagger: # swagger
    protocol: https
    host: staging.jakduk.com:8080
  slackLog: # alert slack
    enabled: true
    level: WARN
    webhook: https://hooks.slack.com/services/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
    channel: #jakduk_staging_log
    username: \uC791\uB450\uD0B9 \uC2EC\uD310