spring:
  http:
    multipart:
      max-file-size: 8MB
  mvc:
    locale: ko_KR
    throw-exception-if-no-handler-found: true

api:
  url-path:
    user-picture-large: user/picture
    user-picture-small: user/picture/small
    gallery-image: gallery
    gallery-thumbnail: gallery/thumbnail

web:
  path:
    board:
      free: board/free