spring:
  profiles:
    include: core-default

server:
  session:
    timeout: 3600 # 1 hour

logging:
  level:
    root: DEBUG
    org.mongodb.driver.cluster: INFO

api:
  api-server-url: http://localhost:8080
  web-server-url: http://localhost:3000
  remember-me-expiration: 7200 # 2 hours
  swagger: # swagger
    protocol: http
    host: localhost:8080
  slackLog: # alert slack
    enabled: false
    level: DEBUG
    webhook: https://hooks.slack.com/services/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
    channel: #jakduk_staging_log
    username: \uC791\uB450\uD0B9 \uC2EC\uD310