spring:
  http:
    multipart:
      max-file-size: 8MB
  mvc:
    locale: ko_KR
    throw-exception-if-no-handler-found: true

api:
  path:
    user:
      picture:
        url:
          large: user/picture
          small: user/picture/small
    gallery:
      url:
         image: gallery
         thumbnail: gallery/thumbnail
web:
  path:
    board:
      free: board/free


facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me