logging:
    level:
        org:
            mongodb:
                driver:
                    cluster: INFO
        root: DEBUG
spring:
    data:
        elasticsearch:
            cluster-name: jakduk-elasticsearch
            cluster-nodes: 192.168.35.137:9300,192.168.35.181:9300
            repositories:
                enabled: false

core:
    elasticsearch:
        bulk:
            actions: 10000
            concurrent:
                requests: 2
            flush:
                interval:
                    seconds: 10
            size:
                mb: 50
        enable: false
        index:
            board: jakduk_dev_board
            gallery: jakduk_dev_gallery
            search:
                word: jakduk_dev_search_word
    email:
        enable: false
    slack:
        board:
            channel: '#jakduk_board_noti'
            enabled: false
            webhook: https://hooks.slack.com/services/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
    storage:
        image:
            path: /Users/pyohwanjang/storage/image/
        thumbnail:
            path: /Users/pyohwanjang/storage/thumbnail/
        user:
            picture:
                large:
                    path: /Users/pyohwanjang/storage/user/picture/large/
                small:
                    path: /Users/pyohwanjang/storage/user/picture/small/
mongo:
    db:
        name: jakduk_test
    host:
        name: http://192.168.35.194:27017,http://192.168.35.138:27017

